{% set version = '3.4.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ergm.count
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ergm.count_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ergm.count/ergm.count_{{ version }}.tar.gz
  sha256: 7c24c79d0901c18991cce907306a1531cca676ae277c6b0a0e4962ad27c36baf

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ergm >=3.10.1
    - r-network >=1.15
    - r-statnet.common >=4.2.0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-ergm >=3.10.1
    - r-network >=1.15
    - r-statnet.common >=4.2.0

test:
  commands:
    - $R -e "library('ergm.count')"           # [not win]
    - "\"%R%\" -e \"library('ergm.count')\""  # [win]

about:
  home: http://statnet.org
  license: GPL-3
  summary: A set of extensions for the 'ergm' package to fit weighted networks whose edge weights
    are counts.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - stevierene82

# Package: ergm.count
# Version: 3.4.0
# Date: 2019-05-15
# Title: Fit, Simulate and Diagnose Exponential-Family Models for Networks with Count Edges
# Authors@R: c( person("Pavel N.", "Krivitsky", role=c("aut","cre"), email="pavel@uow.edu.au", comment=c(ORCID="0000-0002-9101-3362")), person("Mark S.", "Handcock", role=c("ctb"), email="handcock@stat.ucla.edu"), person("David R.", "Hunter", role=c("ctb"), email="dhunter@stat.psu.edu"))
# Depends: ergm (>= 3.10.1), network (>= 1.15)
# Imports: statnet.common (>= 4.2.0)
# LinkingTo: ergm
# Description: A set of extensions for the 'ergm' package to fit weighted networks whose edge weights are counts.
# License: GPL-3 + file LICENSE
# URL: http://statnet.org
# BugReports: https://github.com/statnet/ergm.count/issues
# NeedsCompilation: yes
# Packaged: 2019-05-15 04:52:08 UTC; pavel
# Author: Pavel N. Krivitsky [aut, cre] (<https://orcid.org/0000-0002-9101-3362>), Mark S. Handcock [ctb], David R. Hunter [ctb]
# Maintainer: Pavel N. Krivitsky <pavel@uow.edu.au>
# Repository: CRAN
# Date/Publication: 2019-05-15 07:42:59 UTC
