{% set version = "3.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ergm.count
  version: {{ version|replace("-", "_") }}

source:
  fn: ergm.count_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ergm.count_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ergm.count/ergm.count_{{ version }}.tar.gz
  sha256: e14b4c973d3bde3adc15ebbda5443866678f3919bf5e942bf7a8b6bcd4ea93a0

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]

  host:
    - r-base
    - r-ergm >=3.4
    - r-network
    - r-statnet.common >=3.1

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-ergm >=3.4
    - r-network
    - r-statnet.common >=3.1

test:
  commands:
    - $R -e "library('ergm.count')"           # [not win]
    - "\"%R%\" -e \"library('ergm.count')\""  # [win]

about:
  home: http://statnet.org
  license: GPL-3
  summary: A set of extensions for the 'ergm' package to fit weighted networks whose edge weights
    are counts.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - stevierene82
