# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "aWeLXi29PSMj9gQlV/wHxCrGfu/J6fxuOC4t9O1XyoxwnwTAUM4+WJotOfRMh+4Up7rNCdPkgYJcN0MBcT9WMRr1wsDu1rpBKLYUQOVGBCWwsb5AiJH1JskVsdO9Y2rZFTAdKu5C/DxKyn29RO52kwPPES1DZfPYt/XXOjA6tm7MOO/6oBrE4DiAvDaPS4Q6XB/rRAdpGwqtHhRDf2FZ1zuqdUAO3Goh8IKAyivQ7mmhWl221vP1xsHIuA5EYDSrvr+40LhlS1i3N/EKNpHkRhDYlnwTRotYG4wV9gmEDkFTlCNCCvKMBy+0b6Z1fl5oTRgKq8Jp2oSDSyiftPRA8Ag4ywmKmb+oRFKzFflooQVoPy1inxO+uWXpLwgXKYyLY4bX/m0PGoia6YZpbbDxbVoO1Gg6CybG7Cwk+T/l1TPgJDQ8e+FK+u271tqNh0bPQk83CMjwTn4bvNX5UMk3D8/ICRyVEM9THbUXxja7QYjZy2GHcv+73ZY6laSI926saJNaTI+wHSHThCnDJkVMOh09e4LpqoWqxQdXrzwNi9aWZMB3RnHoOz41WCZ5Ugnqt4I7jrEmFlD+WOFXjWdEh8DH5otUmFDxi9v+Yajcc5EQy1WN5wP9iP3LrlpU+QvXyphPlBXdbOKsoZcKD/eN0QfogvYNnmefVNUMJPlYUdc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
