travis:
  secure:
    BINSTAR_TOKEN: aWeLXi29PSMj9gQlV/wHxCrGfu/J6fxuOC4t9O1XyoxwnwTAUM4+WJotOfRMh+4Up7rNCdPkgYJcN0MBcT9WMRr1wsDu1rpBKLYUQOVGBCWwsb5AiJH1JskVsdO9Y2rZFTAdKu5C/DxKyn29RO52kwPPES1DZfPYt/XXOjA6tm7MOO/6oBrE4DiAvDaPS4Q6XB/rRAdpGwqtHhRDf2FZ1zuqdUAO3Goh8IKAyivQ7mmhWl221vP1xsHIuA5EYDSrvr+40LhlS1i3N/EKNpHkRhDYlnwTRotYG4wV9gmEDkFTlCNCCvKMBy+0b6Z1fl5oTRgKq8Jp2oSDSyiftPRA8Ag4ywmKmb+oRFKzFflooQVoPy1inxO+uWXpLwgXKYyLY4bX/m0PGoia6YZpbbDxbVoO1Gg6CybG7Cwk+T/l1TPgJDQ8e+FK+u271tqNh0bPQk83CMjwTn4bvNX5UMk3D8/ICRyVEM9THbUXxja7QYjZy2GHcv+73ZY6laSI926saJNaTI+wHSHThCnDJkVMOh09e4LpqoWqxQdXrzwNi9aWZMB3RnHoOz41WCZ5Ugnqt4I7jrEmFlD+WOFXjWdEh8DH5otUmFDxi9v+Yajcc5EQy1WN5wP9iP3LrlpU+QvXyphPlBXdbOKsoZcKD/eN0QfogvYNnmefVNUMJPlYUdc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
